In [1]:
# In this FILE I DON'T UPLOAD THE NUMPY BY PIP INSTALL NUMPY 
# I SIMPLE IMPORT BY THE IMPORT NUMPY
# IN THIS FILE I INSTALL THE LIBARARY IN THE VIRTUAL ENV. SO IN FUTURE USE I DON'T HAVE TO UPLOAD THE LIBARAY EACH TIME 
# I USE THE NEW FILE 





# addition of the list in the numpy module
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array([2,3,4])

In [6]:
b

array([2, 3, 4])

In [7]:
c = a + b

In [8]:
c

array([3, 5, 7])

In [9]:
# Additon of the two list in python 

In [26]:
d = [1,3,4]
e = [2,5,6]

In [11]:
f = d + e   #here  e list  is apppend to the list e and f made only append operation happen not addition

In [18]:
print(type(d))
print(type(e))

<class 'list'>
<class 'list'>


In [27]:
f=[]
print(type(f))
for i in range(len(d)):
    f.append(a[i] *b[i])

<class 'list'>


In [28]:
f

[3, 5, 7]