In [1]:
import numpy as np

In [3]:
# Set seed for reproducibility
np.random.seed(seed=2)

In [7]:
import random  
random.seed(1)
for i in range(5):
    print(random.randint(1, 1000))
    

138
583
868
822
783


# Tensor = collection of the values 
scalar(0D tensor) -- 3
vector (1D tesnor)----[1,2,3] [1
                               2
                               3]
matrix (2D tensor)--- [1 2
                        3 4]

3D Tensor


In [2]:
# scalar tesnor

a = np.array(2)
a

array(2)

In [5]:
#num of demesions 
print('num of the dimensios', a.ndim)
print('shape of the ',a.shape)
print('size',a.size)
print('datatype', a.dtype)
print('item size',a.itemsize)
print('type of a ',type(a))

num of the dimensios 0
shape of the  ()
size 1
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [10]:
#1-d tensor vector 
b = np.array([1,2,3,4])
print('num of the dimensios', b.ndim)
print('shape of the ',b.shape)
print('size',b.size)
print('datatype', b.dtype)
print('item size',b.itemsize)
print('type of a ',type(b))

num of the dimensios 1
shape of the  (4,)
size 4
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [14]:
#2-d tensor
matrix
c = np.array([[1,2,6],[3,4,6]])
print('num of the dimensios', c.ndim)
print('shape of the ',c.shape)
print('size',c.size)
print('datatype', c.dtype)
print('item size',c.itemsize)
print('type of a ',type(c))

num of the dimensios 2
shape of the  (2, 3)
size 6
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [15]:
#3-d tensor
#array has 2 rows and 3 columns 
d = np.array([[[1,2,6],[3,4,6]],[[1,2,3],[122,33,44]]])
print('num of the dimensios', d.ndim)
print('shape of the ',d.shape)
print('size',d.size)
print('datatype', d.dtype)
print('item size',d.itemsize)
print('type of a ',type(d))

num of the dimensios 3
shape of the  (2, 2, 3)
size 12
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [17]:
c[0][0]

1

In [18]:
c

array([[1, 2, 6],
       [3, 4, 6]])

In [19]:
a

array(2)

In [20]:
b

array([1, 2, 3, 4])

In [21]:
d

array([[[  1,   2,   6],
        [  3,   4,   6]],

       [[  1,   2,   3],
        [122,  33,  44]]])

In [31]:
#functions for creationg the tesnor


# Functions
print ("zero functions :\n", np.zeros(2))
print ("zero functions :\n", np.zeros(3))    # 3 tell us about the number of coulumn in the matrix
print ("zero functions :\n", np.zeros((1,3)))
print ("zero functions :\n", np.zeros((2,3)))
print ("zero functions :\n", np.zeros((5,3)))





zero functions :
 [0. 0.]
zero functions :
 [0. 0. 0.]
zero functions :
 [[0. 0. 0.]]
zero functions :
 [[0. 0. 0.]
 [0. 0. 0.]]
zero functions :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
#functions for creationg the tesnor


#functions for creationg the tesnor


# Functions
print ("zero functions :\n", np.ones(2))
print ("zero functions :\n", np.ones(3))    # 3 tell us about the number of coulumn in the matrix
print ("zero functions :\n", np.ones((1,3)))
print ("zero functions :\n", np.ones((2,3)))
print ("zero functions :\n",np.ones((5,3)))


array_A =  np.ones(2)
array_b = np.ones((1,3))
print(array_A.ndim)
print(array_b.ndim)

zero functions :
 [1. 1.]
zero functions :
 [1. 1. 1.]
zero functions :
 [[1. 1. 1.]]
zero functions :
 [[1. 1. 1.]
 [1. 1. 1.]]
zero functions :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1
2


In [36]:
print ("eye functionsfunctions ", np.eye((2))) # identity matrix 
print ("np.random.random functrions", np.random.random((2,2)))

eye functionsfunctions  [[1. 0.]
 [0. 1.]]
np.random.random functrions [[0.84883287 0.43832955]
 [0.00218404 0.36700507]]


In [37]:
index_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [39]:
index_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
index_A[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [41]:
index_A[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
index_A[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [43]:
# Integer array indexing
print (index_A)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", index_A[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [45]:


# Boolean array indexing
x = np.array([[1, 8], [3, 14], [5, 6]])
print ("x:\n", x)
print ("x > 5:\n", x > 5)
print ("x[x > 5]:\n", x[x > 5])



x:
 [[ 1  8]
 [ 3 14]
 [ 5  6]]
x > 5:
 [[False  True]
 [False  True]
 [False  True]]
x[x > 5]:
 [ 8 14  6]


# Arithmatic operation

In [47]:


# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[12,22], [23,24]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y



x + y:
 [[13. 24.]
 [26. 28.]]
x - y:
 [[-11. -20.]
 [-20. -20.]]
x * y:
 [[12. 44.]
 [69. 96.]]


In [50]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[17,8], [9,12], [11, 22]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 68.  98.]
 [179. 224.]]


# Axis operations : we can also perform operation through axis
    
    

In [53]:
axis_operations = np.array([1,2])
print('sum of all element matrix',np.sum(axis_operations))


sum of all element matrix 3


In [61]:
axis_operations_2d = np.array([[0,1],[2,3]])
print(axis_operations_2d)
print('sum of all element matrix',np.sum(axis_operations_2d))
print('sum of all element matrix along rowa',np.sum(axis_operations_2d,axis=1))
print('sum of all element matrix along column',np.sum(axis_operations_2d,axis=0))

[[0 1]
 [2 3]]
sum of all element matrix 6
sum of all element matrix along rowa [1 5]
sum of all element matrix along column [2 4]


# numpy.sum() in Python

numpy.sum(arr, axis, dtype, out) : This function returns the sum of array elements over the specified axis.

    Parameters :
    arr : input array.
    axis : axis along which we want to calculate the sum value. Otherwise, it will consider arr to be flattened(works on all the axis). axis = 0 means along the column and axis = 1 means working along the row.
    out : Different array in which we want to place the result. The array must have same dimensions as expected output. Default is None.
    initial : [scalar, optional] Starting value of the sum.

    Return : Sum of the array elements (a scalar value if axis is none) or array with sum values along the specified axis.

In [64]:
# Min/max
x = np.array([[1222,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0 aliong column: ", x.min(axis=0))
print ("min axis=1 along row: ", x.min(axis=1))

min:  2
max:  1222
min axis=0 aliong column:  [4 2 3]
min axis=1 along row:  [2 4]


# Array Broadcasting in Numpy

Let’s explore a more advanced concept in numpy called broadcasting. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. This article provides a gentle introduction to broadcasting with numerous examples ranging from simple to involved. It also provides hints on when and when not to use broadcasting.

numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape:

In [65]:
broad = np.array([1,2,33])
broad_a = 5
print(broad * broad_a)

[  5  10 165]
