In [1]:
import numpy as np

In [2]:
# Set seed for reproducibility
np.random.seed(seed=2)

In [3]:
import random  
random.seed(1)
for i in range(5):
    print(random.randint(1, 1000))
    

138
583
868
822
783


# Tensor = collection of the values 
scalar(0D tensor) -- 3
vector (1D tesnor)----[1,2,3] [1
                               2
                               3]
matrix (2D tensor)--- [1 2
                        3 4]

3D Tensor


In [4]:
# scalar tesnor

a = np.array(2)
a

array(2)

In [5]:
#num of demesions 
print('num of the dimensios', a.ndim)
print('shape of the ',a.shape)
print('size',a.size)
print('datatype', a.dtype)
print('item size',a.itemsize)
print('type of a ',type(a))

num of the dimensios 0
shape of the  ()
size 1
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [6]:
#1-d tensor vector 
b = np.array([1,2,3,4])
print('num of the dimensios', b.ndim)
print('shape of the ',b.shape)
print('size',b.size)
print('datatype', b.dtype)
print('item size',b.itemsize)
print('type of a ',type(b))

num of the dimensios 1
shape of the  (4,)
size 4
datatype int64
item size 8
type of a  <class 'numpy.ndarray'>


In [7]:
#2-d tensor
matrix
c = np.array([[1,2,6],[3,4,6]])
print('num of the dimensios', c.ndim)
print('shape of the ',c.shape)
print('size',c.size)
print('datatype', c.dtype)
print('item size',c.itemsize)
print('type of a ',type(c))

NameError: name 'matrix' is not defined

In [ ]:
#3-d tensor
#array has 2 rows and 3 columns 
d = np.array([[[1,2,6],[3,4,6]],[[1,2,3],[122,33,44]]])
print('num of the dimensios', d.ndim)
print('shape of the ',d.shape)
print('size',d.size)
print('datatype', d.dtype)
print('item size',d.itemsize)
print('type of a ',type(d))

In [ ]:
c[0][0]

In [ ]:
c

In [ ]:
a

In [ ]:
b

In [ ]:
d

In [ ]:
#functions for creationg the tesnor


# Functions
print ("zero functions :\n", np.zeros(2))
print ("zero functions :\n", np.zeros(3))    # 3 tell us about the number of coulumn in the matrix
print ("zero functions :\n", np.zeros((1,3)))
print ("zero functions :\n", np.zeros((2,3)))
print ("zero functions :\n", np.zeros((5,3)))





In [ ]:
#functions for creationg the tesnor


#functions for creationg the tesnor


# Functions
print ("zero functions :\n", np.ones(2))
print ("zero functions :\n", np.ones(3))    # 3 tell us about the number of coulumn in the matrix
print ("zero functions :\n", np.ones((1,3)))
print ("zero functions :\n", np.ones((2,3)))
print ("zero functions :\n",np.ones((5,3)))


array_A =  np.ones(2)
array_b = np.ones((1,3))
print(array_A.ndim)
print(array_b.ndim)

In [ ]:
print ("eye functionsfunctions ", np.eye((2))) # identity matrix 
print ("np.random.random functrions", np.random.random((2,2)))

In [ ]:
index_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
index_A

In [ ]:
index_A[0:2,1:3]

In [ ]:
index_A[0:2]

In [ ]:
index_A[:,1:3]

In [ ]:
# Integer array indexing
print (index_A)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", index_A[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

In [ ]:


# Boolean array indexing
x = np.array([[1, 8], [3, 14], [5, 6]])
print ("x:\n", x)
print ("x > 5:\n", x > 5)
print ("x[x > 5]:\n", x[x > 5])



# Arithmatic operation

In [ ]:


# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[12,22], [23,24]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y



In [ ]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[17,8], [9,12], [11, 22]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

# Axis operations : we can also perform operation through axis
    
    

In [ ]:
axis_operations = np.array([1,2])
print('sum of all element matrix',np.sum(axis_operations))


In [ ]:
axis_operations_2d = np.array([[0,1],[2,3]])
print(axis_operations_2d)
print('sum of all element matrix',np.sum(axis_operations_2d))
print('sum of all element matrix along rowa',np.sum(axis_operations_2d,axis=1))
print('sum of all element matrix along column',np.sum(axis_operations_2d,axis=0))

# numpy.sum() in Python

numpy.sum(arr, axis, dtype, out) : This function returns the sum of array elements over the specified axis.

    Parameters :
    arr : input array.
    axis : axis along which we want to calculate the sum value. Otherwise, it will consider arr to be flattened(works on all the axis). axis = 0 means along the column and axis = 1 means working along the row.
    out : Different array in which we want to place the result. The array must have same dimensions as expected output. Default is None.
    initial : [scalar, optional] Starting value of the sum.

    Return : Sum of the array elements (a scalar value if axis is none) or array with sum values along the specified axis.

In [ ]:
# Min/max
x = np.array([[1222,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0 aliong column: ", x.min(axis=0))
print ("min axis=1 along row: ", x.min(axis=1))

# Array Broadcasting in Numpy

Let’s explore a more advanced concept in numpy called broadcasting. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. This article provides a gentle introduction to broadcasting with numerous examples ranging from simple to involved. It also provides hints on when and when not to use broadcasting.

numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape:

In [ ]:
broad = np.array([1,2,33])
broad_a = 5
print(broad * broad_a)

# Transpose
The transpose of a matrix is a new matrix whose rows are the columns of the original.
Another way to look at the transpose is that the element at row r column 

# Another way to look at the transpose is that the element at row r column c in the original is placed at row c column r of the transpose. The element arc of the original matrix becomes element acr in the transposed matrix.

In [8]:
# Transposing
x = np.array([[1,2,3,11,12,13], [4,5,6,7,8,9]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

x:
 [[ 1  2  3 11 12 13]
 [ 4  5  6  7  8  9]]
x.shape:  (2, 6)
y:
 [[ 1  4]
 [ 2  5]
 [ 3  6]
 [11  7]
 [12  8]
 [13  9]]
y.shape:  (6, 2)


In [9]:
# Transposing
x = np.array([[1,2,3,11,12,13], [4,5,6,7,8,9], [111,222,333,444,555,666]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

x:
 [[  1   2   3  11  12  13]
 [  4   5   6   7   8   9]
 [111 222 333 444 555 666]]
x.shape:  (3, 6)
y:
 [[  1   4 111]
 [  2   5 222]
 [  3   6 333]
 [ 11   7 444]
 [ 12   8 555]
 [ 13   9 666]]
y.shape:  (6, 3)


In [10]:
# Reshaping
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [11]:
# Reshaping
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (3, 2))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2]
 [3 4]
 [5 6]]
y.shape:  (3, 2)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [15]:
# Reshaping
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (6, 1))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (1, -3))
print ("z: \n", z)
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
y.shape:  (6, 1)
z: 
 [[1 2 3 4 5 6]]
z.shape:  (1, 6)


# Adding/removing dimensions

We can also easily add and remove dimensions to our tensors and we'll want to do this to make tensors compatible for certain operations.


In [17]:
# Adding dimensions
x = np.array([[1,2,3],[4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 2) # expand dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
y.shape:  (2, 3, 1)


In [18]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone


x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
