In [2]:
pip install -r requirements.txt

  ERROR: Could not find a version that satisfies the requirement sys (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for sys (from -r requirements.txt (line 8))
Note: you may need to restart the kernel to use updated packages.


In [7]:
print('hello')

hello


In [5]:
import sys

In [6]:
import time

In [8]:
a = [1,2,3,4]
b = [4,5,6,7]
c = a * b 

TypeError: can't multiply sequence by non-int of type 'list'

In [10]:
c = []
for i in range(len(a)):
    c.append(a[i]* b[i])

In [11]:

c

[4, 10, 18, 28]

In [13]:
import numpy as np
anp = np.array([1,2,3,4])
bnp = np.array([4,5,6,7])
c = anp * bnp
c

array([ 4, 10, 18, 28])

In [14]:
print(c)

[ 4 10 18 28]


In [15]:
c.ndim

1

In [16]:
a = np.arange(15).reshape(3, 5)

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.ndim

2

In [20]:
c


array([ 4, 10, 18, 28])

In [21]:
c.ndim

1

In [22]:
c = c + np.array([1,2,34,5])

In [23]:
c

array([ 5, 12, 52, 33])

In [27]:
c = np.array([1,2,3])

In [28]:
c

array([1, 2, 3])

In [29]:
c.ndim

1

In [32]:
a = np.array([[[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]])

In [33]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [34]:
a.ndim

3

In [35]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [37]:
a.ndim

1

In [40]:
a = np.array([1,2,3,4],[1,2,34,4])

TypeError: data type not understood

In [41]:
a = np.array([[1,2,3,4],[1,2,34,4]])

In [42]:
a
a.ndim

2

In [43]:
a = np.array([[1,2,3,4],[1,2,34,4]],[1,2,3])

TypeError: data type not understood

In [44]:
a = np.array([[[1,2,3,4],[1,2,34,4]],[1,2,3]])

In [45]:
a
a.ndim

1

In [46]:
a[0]

[[1, 2, 3, 4], [1, 2, 34, 4]]

In [47]:
a[0].ndim

AttributeError: 'list' object has no attribute 'ndim'

In [48]:
check_a = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
check_a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
print('the number of axes (dimensions) of the array.====',check_a.ndim)
print('matrix with n rows and m columns, shape will be (n,m).====',check_a.shape)
print("the total number of elements of the array. ===",check_a.size)
print('an object describing the type of the elements in the array.===',check_a.dtype)
print('the size in bytes of each element of the array ===',check_a.itemsize)

the number of axes (dimensions) of the array.==== 2
matrix with n rows and m columns, shape will be (n,m).==== (3, 5)
the total number of elements of the array. === 15
an object describing the type of the elements in the array.=== int64
the size in bytes of each element of the array === 8


In [65]:
check_a = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]],dtype='float')
check_a


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [66]:
print('the number of axes (dimensions) of the array.====',check_a.ndim)
print('matrix with n rows and m columns, shape will be (n,m).====',check_a.shape)
print("the total number of elements of the array. ===",check_a.size)
print('an object describing the type of the elements in the array.===',check_a.dtype)
print('the size in bytes of each element of the array ===',check_a.itemsize)

the number of axes (dimensions) of the array.==== 2
matrix with n rows and m columns, shape will be (n,m).==== (3, 5)
the total number of elements of the array. === 15
an object describing the type of the elements in the array.=== float64
the size in bytes of each element of the array === 8


In [67]:
type(check_a)

numpy.ndarray

In [68]:
type(check_a)

numpy.ndarray

In [69]:
a = np.array(1,2,34)

ValueError: only 2 non-keyword arguments accepted

In [70]:
a = np.array(1,2)

TypeError: data type not understood

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [80]:
b = np.array([[15,2,3], [4,5,6],[7,8,9]])
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)

3
(1, 3, 3)
9
8


In [78]:
b = np.array([15,2,3], [4,5,6],[7,8,9])
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)

ValueError: only 2 non-keyword arguments accepted

In [81]:
b = np.array([[[15,2,3], [4,5,6],[7,8,9]]])
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)

3
(1, 3, 3)
9
8


# The type of the array can also be explicitly specified at creation time:

In [82]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

# the function zeros creates an array full of zeros,

In [83]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# the function ones creates an array full of ones, 

In [85]:
 a = np.ones( (2,3,4), dtype=np.int16 )  

In [86]:
a.ndim

3

In [87]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [88]:
a.dtype

dtype('int16')

In [91]:
 b = np.ones( (2,3,4))  

In [92]:
b.ndim

3

In [93]:
b.dtype

dtype('float64')

In [94]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [97]:
empty =  np.empty( (2,3) )  

In [98]:
empty.dtype

dtype('float64')

In [101]:
#To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
print(np.arange( 10, 30, 5 ))

print(np.arange( 0, 2, 0.3 )   )              # it accepts float arguments




[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [103]:
check_a = np.arange( 10, 30, 5 )
type(check_a)

numpy.ndarray

In [104]:
check_a

array([10, 15, 20, 25])

In [105]:
print(check_a)

[10 15 20 25]
